version: "3"
services:
  fake_api:
    image: wiremock/wiremock:2.33.2
    ports:
      - "18080:8080"
    volumes:
      - ./api_stubs:/home/wiremock/mappings
    command:
      - --verbose
  kraken_designer:
    image: devopsfaith/krakendesigner:v2.0
    ports:
      - 8787:80
  api_gateway:
#    image: devopsfaith/krakend:watch # use this for hot-reload enabled krakend, only recommended for development
#    image: devopsfaith/krakend:2.0.5
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./krakend:/etc/krakend
      - .:/usr/src/api-gateway
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    command: [ "run", "-c", "/etc/krakend/krakend.json" ]
    depends_on:
      - fake_api
      - awslocal
    environment:
      USAGE_DISABLE: 1
      SEQUENTIAL_START: false
      S3_ENDPOINT: "http://awslocal:4566"
      AWS_DEFAULT_REGION: eu-west-1

  api_gateway_fc:
    image: devopsfaith/krakend:2.0.5
    volumes:
      - ./krakend-fc:/etc/krakend
    ports:
      - "21234:1234"
      - "28080:8080"
      - "28090:8090"
    command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]
    #    command: ["check", "-t", "-d", "-c", "/etc/krakend/krakend.json"]
    environment:
      FC_ENABLE: 1
      FC_SETTINGS: "/etc/krakend/settings/prod"
      FC_PARTIALS: "/etc/krakend/partials"
      FC_TEMPLATES: "/etc/krakend/templates"
      FC_OUT: "/etc/krakend/out.json"
    depends_on:
      - fake_api

  awslocal:
    image: localstack/localstack:0.12.16
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"
      DEFAULT_REGION: eu-west-1
      SERVICES: "s3"
    ports:
      - "4566:4566"
    volumes:
      - localstackdata:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  localstackdata: ~
